# Generated by Django 5.2.17 on 2026-08-15 04:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('state_version', models.PositiveIntegerField()),
                ('decision', models.CharField(max_length=200)),
                ('resolution_logic', models.TextField()),
                ('input_events', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_replay', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('LMS', 'Learning Management System'), ('IOT', 'Classroom IoT Device'), ('ATTENDANCE', 'Attendance System')], max_length=20)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('quiz_attempt', 'Quiz Attempt'), ('device_present', 'Device Present'), ('device_absent', 'Device Absent'), ('attendance_marked', 'Attendance Marked')], max_length=30)),
                ('event_timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField()),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['event_timestamp', 'received_at'],
                'indexes': [models.Index(fields=['user_id'], name='recon_rawev_user_id_424179_idx'), models.Index(fields=['event_timestamp'], name='recon_rawev_event_t_e0055f_idx'), models.Index(fields=['fingerprint'], name='recon_rawev_fingerp_2ba9fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_logout', models.DateTimeField(blank=True, null=True)),
                ('is_device_present', models.BooleanField(default=False)),
                ('last_device_present', models.DateTimeField(blank=True, null=True)),
                ('last_device_absent', models.DateTimeField(blank=True, null=True)),
                ('quiz_attempts', models.PositiveIntegerField(default=0)),
                ('last_quiz_attempt', models.DateTimeField(blank=True, null=True)),
                ('timeline', models.JSONField(default=list)),
                ('triggered_by_events', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['user_id', 'version'],
                'unique_together': {('user_id', 'version')},
            },
        ),
    ]
